INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2014-chevrolet-cruze-1052',
    '2014 Chevrolet Cruze',
    'one touch windows, folding side/driver mirror, cruise, 12v power outlet, ',
    9999,
    'for-sale',
    '103,903 miles',
    '2014',
    'Chevrolet',
    'Cruze',
    '1G1PB5SG7E7352046',
    '1052',
    'DARK GREEN',
    'Tan',
    null,
    null,
    null,
    '["https://lh3.googleusercontent.com/d/14nKcHrwgfPzk34H7WReO20nNZgbPDXoO=w800","https://lh3.googleusercontent.com/d/1V1YvrqpskSHa7Fb19gGfWoLjPf9mpn_4=w800","https://lh3.googleusercontent.com/d/1taYD4NiJHehVqH2yOvDncfxhXyWPUtMM=w800","https://lh3.googleusercontent.com/d/13nj6gsMpG8Q0gUJcEOinJnlc67qPljkd=w800","https://lh3.googleusercontent.com/d/1wlWne8TCQQABPkySaDIKNMv6Jc6PXZxG=w800","https://lh3.googleusercontent.com/d/1ZViAX4rgbt3nbLH_OmyGM2Zg6cKcHCfU=w800"]',
    '[]',
    '2014 Chevrolet Cruze - T-Rex Motors Richmond, IN',
    '2014 Chevrolet Cruze for sale at T-Rex Motors. one touch windows, folding side/driver mirror, cruise, 12v power outlet, ... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2015-buick-enclave-1053',
    '2015 BUICK ENCLAVE',
    'Back up camera, heated/cooled seats, power everything',
    14999,
    'for-sale',
    '113,800 miles',
    '2015',
    'BUICK',
    'ENCLAVE',
    '5GAKVCKD7FJ328533',
    '1053',
    'RED',
    'beige',
    null,
    null,
    null,
    '["https://storage.googleapis.com/msgsndr/QjiQRR74D1pxPF7I8fcC/media/8917743c-1709-41eb-ab41-244dea63cd32.jpeg","https://storage.googleapis.com/msgsndr/QjiQRR74D1pxPF7I8fcC/media/cfd3936e-20cc-4858-bb65-9f257ffcdd3c.jpeg","https://storage.googleapis.com/msgsndr/QjiQRR74D1pxPF7I8fcC/media/0b08d17a-8440-4951-953b-c121a0d584ed.jpeg"]',
    '[]',
    '2015 BUICK ENCLAVE - T-Rex Motors Richmond, IN',
    '2015 BUICK ENCLAVE for sale at T-Rex Motors. Back up camera, heated/cooled seats, power everything... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2019-chevrolet-traverse-1055',
    '2019 CHEVROLET TRAVERSE',
    'Backup Camera; Cloth Seats; Heated Passenger Seat; Heated Driver',
    19999,
    'for-sale',
    '94,186 miles',
    '2019',
    'CHEVROLET',
    'TRAVERSE',
    '1GNEVGKW9KJ260256',
    '1055',
    'GRAY',
    'black',
    null,
    null,
    null,
    '["https://lh3.googleusercontent.com/d/1y-UBx90V15x2P0vIqTUOk85s9ZF9Z5TC=w800","https://lh3.googleusercontent.com/d/1p-Wc7qGPZCl6AChaSKehcQu4-_nw75BT=w800","https://lh3.googleusercontent.com/d/1dy8K-aqnXB6qvhcVszmtKqDtm3DtnrDR=w800","https://lh3.googleusercontent.com/d/123CwYsiUU-2Okd8un0AvAzJxaxqeoCsI=w800","https://lh3.googleusercontent.com/d/1dTmTEFiFiTynh6fuxBQfcg49RYkmvEji=w800"]',
    '[]',
    '2019 CHEVROLET TRAVERSE - T-Rex Motors Richmond, IN',
    '2019 CHEVROLET TRAVERSE for sale at T-Rex Motors. Backup Camera; Cloth Seats; Heated Passenger Seat; Heated Driver... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2013-ford-flex-sel-1008',
    '2013 Ford Flex SEL',
    '2013 Ford Flex SEL in excellent condition.',
    8481,
    'for-sale',
    '155,359 miles',
    '2013',
    'Ford',
    'Flex SEL',
    '2FMGK5C87DBD26742',
    '1008',
    'white',
    'grey',
    null,
    null,
    null,
    '[]',
    '[]',
    '2013 Ford Flex SEL - T-Rex Motors Richmond, IN',
    '2013 Ford Flex SEL for sale at T-Rex Motors. ... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2020-dodge-charger-1021',
    '2020 Dodge Charger',
    'Backup Camera; Cloth Seats; Remote Start; Dual A/C Zones;',
    17999,
    'for-sale',
    '96,627 miles',
    '2020',
    'Dodge',
    'Charger',
    '2C3CDXBG7LH119687',
    '1021',
    'White',
    'Black',
    null,
    null,
    null,
    '[]',
    '[]',
    '2020 Dodge Charger - T-Rex Motors Richmond, IN',
    '2020 Dodge Charger for sale at T-Rex Motors. Backup Camera; Cloth Seats; Remote Start; Dual A/C Zones;... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2014-jeep-grand-cherokee-1024',
    '2014 Jeep Grand Cherokee',
    'Cloth Seats; Dual A/C Zones; Automatic Climate Control; Front Fog',
    12999,
    'for-sale',
    '120,955 miles',
    '2014',
    'Jeep',
    'Grand Cherokee',
    '1C4RJFAG9EC422180',
    '1024',
    'Red',
    'Grey',
    null,
    null,
    null,
    '[]',
    '[]',
    '2014 Jeep Grand Cherokee - T-Rex Motors Richmond, IN',
    '2014 Jeep Grand Cherokee for sale at T-Rex Motors. Cloth Seats; Dual A/C Zones; Automatic Climate Control; Front Fog... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2018-honda-civic-1027',
    '2018 Honda Civic',
    'Backup Camera; Cloth Seats; Automatic Climate Control; Moonroof/Sunroof;',
    17999,
    'for-sale',
    '98,964 miles',
    '2018',
    'Honda',
    'Civic',
    '19XFC2F70JE022722',
    '1027',
    'White',
    'Grey',
    null,
    null,
    null,
    '[]',
    '[]',
    '2018 Honda Civic - T-Rex Motors Richmond, IN',
    '2018 Honda Civic for sale at T-Rex Motors. Backup Camera; Cloth Seats; Automatic Climate Control; Moonroof/Sunroof;... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2015-toyota-corolla-1041',
    '2015 Toyota Corolla',
    'back up camera, power windows, power locks, cruise control, cd player, cloth seats',
    13999,
    'for-sale',
    '74,684 miles',
    '2015',
    'Toyota',
    'Corolla',
    '2T1BURHE3FC436454',
    '1041',
    'Silver',
    'Gray',
    null,
    null,
    null,
    '[]',
    '[]',
    '2015 Toyota Corolla - T-Rex Motors Richmond, IN',
    '2015 Toyota Corolla for sale at T-Rex Motors. back up camera, power windows, power locks, cruise control, cd player, cloth seats... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2018-chevrolet-silverado-lt-1042',
    '2018 Chevrolet Silverado LT',
    'Backup Camera; Cloth Seats; Daytime Running Lights; SiriusXM Equipped;',
    19999,
    'for-sale',
    '125,698 miles',
    '2018',
    'Chevrolet',
    'Silverado LT',
    '1GCRCREH7JZ369615',
    '1042',
    'White',
    'Gray',
    null,
    null,
    null,
    '[]',
    '[]',
    '2018 Chevrolet Silverado LT - T-Rex Motors Richmond, IN',
    '2018 Chevrolet Silverado LT for sale at T-Rex Motors. Backup Camera; Cloth Seats; Daytime Running Lights; SiriusXM Equipped;... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2016-ford-focus-1044',
    '2016 Ford Focus',
    '2016 Ford Focus in excellent condition.',
    8999,
    'for-sale',
    '154,627 miles',
    '2016',
    'Ford',
    'Focus',
    '1FADP3F26GL235069',
    '1044',
    'Silver',
    'Black',
    null,
    null,
    null,
    '[]',
    '[]',
    '2016 Ford Focus - T-Rex Motors Richmond, IN',
    '2016 Ford Focus for sale at T-Rex Motors. ... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2020-chevrolet-malibu-1049',
    '2020 Chevrolet Malibu',
    'Backup Camera; Cloth Seats; Heated Passenger Seat; Heated Driver',
    19999,
    'for-sale',
    '53,747 miles',
    '2020',
    'Chevrolet',
    'Malibu',
    '1G1ZD5STXLF043030',
    '1049',
    'Maroon',
    'Black',
    null,
    null,
    null,
    '[]',
    '[]',
    '2020 Chevrolet Malibu - T-Rex Motors Richmond, IN',
    '2020 Chevrolet Malibu for sale at T-Rex Motors. Backup Camera; Cloth Seats; Heated Passenger Seat; Heated Driver... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2019-dodge-journey-1050',
    '2019 Dodge Journey',
    'Backup Camera; Cloth Seats; Dual A/C Zones; Front Fog Lights; Daytime',
    13499,
    'for-sale',
    '80,889 miles',
    '2019',
    'Dodge',
    'Journey',
    '3C4PDCBB0KT874261',
    '1050',
    'Black',
    'Black',
    null,
    null,
    null,
    '[]',
    '[]',
    '2019 Dodge Journey - T-Rex Motors Richmond, IN',
    '2019 Dodge Journey for sale at T-Rex Motors. Backup Camera; Cloth Seats; Dual A/C Zones; Front Fog Lights; Daytime... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2014-jeep-wrangler-sahara-unlimited-1057',
    '2014 JEEP WRANGLER SAHARA UNLIMITED',
    '"Cloth Seats; Soft Top; Front Fog Lights; Daytime Running Lights;',
    16999,
    'for-sale',
    '176,130 miles',
    '2014',
    'JEEP',
    'WRANGLER SAHARA UNLIMITED',
    '1C4BJWEG0EL300349',
    '1057',
    'GRAY',
    'black',
    null,
    null,
    null,
    '[]',
    '[]',
    '2014 JEEP WRANGLER SAHARA UNLIMITED - T-Rex Motors Richmond, IN',
    '2014 JEEP WRANGLER SAHARA UNLIMITED for sale at T-Rex Motors. "Cloth Seats; Soft Top; Front Fog Lights; Daytime Running Lights;... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2019-hyandai-santa-fe-1060',
    '2019 HYANDAI SANTA FE',
    'Backup Camera; Cloth Seats; Daytime Running Lights; Touch Screen',
    13999,
    'for-sale',
    '122,171 miles',
    '2019',
    'HYANDAI',
    'SANTA FE',
    '5NMS23AD7KH023428',
    '1060',
    'SILVER',
    'black',
    null,
    null,
    null,
    '[]',
    '[]',
    '2019 HYANDAI SANTA FE - T-Rex Motors Richmond, IN',
    '2019 HYANDAI SANTA FE for sale at T-Rex Motors. Backup Camera; Cloth Seats; Daytime Running Lights; Touch Screen... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2020-kia-forte-1061',
    '2020 KIA FORTE',
    'Backup Camera; Cloth Seats; Daytime Running Lights; Touch Screen',
    17999,
    'for-sale',
    '52,972 miles',
    '2020',
    'KIA',
    'FORTE',
    '3KPF24ADXLE140629',
    '1061',
    'WHITE',
    'null',
    null,
    null,
    null,
    '[]',
    '[]',
    '2020 KIA FORTE - T-Rex Motors Richmond, IN',
    '2020 KIA FORTE for sale at T-Rex Motors. Backup Camera; Cloth Seats; Daytime Running Lights; Touch Screen... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2011-chevrolet-impala-1064',
    '2011 CHEVROLET IMPALA',
    '2011 CHEVROLET IMPALA in excellent condition.',
    4999,
    'for-sale',
    '197,000 miles',
    '2011',
    'CHEVROLET',
    'IMPALA',
    '2G1WB5EK8B1236245',
    '1064',
    'RED',
    'Tan',
    null,
    null,
    null,
    '[]',
    '[]',
    '2011 CHEVROLET IMPALA - T-Rex Motors Richmond, IN',
    '2011 CHEVROLET IMPALA for sale at T-Rex Motors. ... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2016-buick-encore-1068',
    '2016 BUICK ENCORE',
    '2016 BUICK ENCORE in excellent condition.',
    10999,
    'for-sale',
    '124,242 miles',
    '2016',
    'BUICK',
    'ENCORE',
    'KL4CJ2SM3GB691491',
    '1068',
    'RED',
    'Tan',
    null,
    null,
    null,
    '[]',
    '[]',
    '2016 BUICK ENCORE - T-Rex Motors Richmond, IN',
    '2016 BUICK ENCORE for sale at T-Rex Motors. ... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

INSERT INTO vehicles (
    slug, title, description, price, status, mileage, year, make, model, 
    vin, "stockNumber", "exteriorColor", "interiorColor", engine, transmission, 
    "driveType", images, "keyFeatures", "metaTitle", "metaDescription", 
    "bannerNew", "bannerReduced", "bannerGreatDeal", "bannerSold"
  ) VALUES (
    '2018-subaru-crosstrek-1070',
    '2018 SUBARU CROSSTREK',
    '------------------------------------------------------------------------',
    18999,
    'for-sale',
    '110,428 miles',
    '2018',
    'SUBARU',
    'CROSSTREK',
    'JF2GTAJC0JH207352',
    '1070',
    'GREY',
    'BLACK/GREY',
    null,
    null,
    null,
    '[]',
    '[]',
    '2018 SUBARU CROSSTREK - T-Rex Motors Richmond, IN',
    '2018 SUBARU CROSSTREK for sale at T-Rex Motors. ------------------------------------------------------------------------... Contact us at 765-238-2887.',
    false,
    false,
    false,
    false
  );

