[build]
  publish = "server/public"
  command = "npm install"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/vehicles"
  to = "/.netlify/functions/vehicles"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200