[build]
  publish = "server/public"
  command = "echo 'No build needed - using static files'"
  ignore = "git diff --quiet $CACHED_COMMIT_REF $COMMIT_REF"

[build.environment]
  NODE_VERSION = "18"
  SKIP_NPM_INSTALL = "true"

[[redirects]]
  from = "/api/vehicles"
  to = "/.netlify/functions/vehicles"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200