import { db } from "./db";
import { vehicles } from "@shared/schema";

async function seedTrexVehicles() {
  console.log("Seeding database with T-Rex Motors inventory...");
  
  // Clear existing data
  await db.delete(vehicles);
  
  const trexVehicles = [
    {
      slug: "2021-kia-forte-red-15991",
      title: "2021 Kia Forte",
      description: "Sporty and efficient compact sedan with modern features and reliable performance.",
      price: 15991,
      year: "2021",
      make: "Kia",
      model: "Forte",
      vin: "KNAFK4A61M5123456",
      stockNumber: "KF001",
      mileage: "75620",
      exteriorColor: "Red",
      interiorColor: "Grey",
      engine: "2.0L 4-Cylinder",
      transmission: "CVT Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6824bd9d8e57c56c455303ea.jpeg"],
      keyFeatures: ["Low Mileage", "Fuel Efficient", "Modern Technology"],
      metaTitle: "2021 Kia Forte - T-Rex Motors Richmond IN",
      metaDescription: "2021 Kia Forte with 75,620 miles. Sporty compact sedan with modern features."
    },
    {
      slug: "2019-gmc-acadia-blue-19999",
      title: "2019 GMC Acadia",
      description: "Spacious 3-row SUV with premium features and excellent towing capacity.",
      price: 19999,
      year: "2019",
      make: "GMC",
      model: "Acadia",
      vin: "1GKKNWLS4KZ123456",
      stockNumber: "GA001",
      mileage: "106861",
      exteriorColor: "Blue",
      interiorColor: "Grey",
      engine: "2.5L 4-Cylinder",
      transmission: "9-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/680cde8a532ba635c6ea5f12.jpeg"],
      keyFeatures: ["3-Row Seating", "Towing Package", "Premium Interior"],
      metaTitle: "2019 GMC Acadia - T-Rex Motors Richmond IN",
      metaDescription: "2019 GMC Acadia with 106,861 miles. Spacious 3-row SUV with premium features."
    },
    {
      slug: "2012-cadillac-cts-black-12500",
      title: "2012 Cadillac CTS",
      description: "Luxury sedan with powerful performance and premium amenities.",
      price: 12500,
      year: "2012",
      make: "Cadillac",
      model: "CTS",
      vin: "1G6DG5E50C0123456",
      stockNumber: "CC001",
      mileage: "93086",
      exteriorColor: "Black",
      interiorColor: "Black",
      engine: "3.6L V6",
      transmission: "6-Speed Automatic",
      driveType: "RWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6824e0e39cd8fb58969a3d54.jpeg"],
      keyFeatures: ["Luxury Interior", "V6 Power", "Premium Sound"],
      metaTitle: "2012 Cadillac CTS - T-Rex Motors Richmond IN",
      metaDescription: "2012 Cadillac CTS with 93,086 miles. Luxury sedan with powerful V6 engine."
    },
    {
      slug: "2020-dodge-charger-white-17999",
      title: "2020 Dodge Charger",
      description: "American muscle sedan with aggressive styling and impressive performance.",
      price: 17999,
      year: "2020",
      make: "Dodge",
      model: "Charger",
      vin: "2C3CDXBG6LH123456",
      stockNumber: "DC001",
      mileage: "96627",
      exteriorColor: "White",
      interiorColor: "Black",
      engine: "3.6L V6",
      transmission: "8-Speed Automatic",
      driveType: "RWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6824d8019cd8fb4e309a1cbe.jpeg"],
      keyFeatures: ["Muscle Car Performance", "Spacious Interior", "Modern Tech"],
      metaTitle: "2020 Dodge Charger - T-Rex Motors Richmond IN",
      metaDescription: "2020 Dodge Charger with 96,627 miles. American muscle sedan with V6 power."
    },
    {
      slug: "2016-buick-enclave-premium-black-15999",
      title: "2016 Buick Enclave Premium",
      description: "Luxury 3-row SUV with premium features and smooth ride quality.",
      price: 15999,
      year: "2016",
      make: "Buick",
      model: "Enclave",
      vin: "5GAKVCKD7GJ123456",
      stockNumber: "BE001",
      mileage: "106721",
      exteriorColor: "Black",
      interiorColor: "Black",
      engine: "3.6L V6",
      transmission: "6-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6824d1f420806f843aedeb13.jpeg"],
      keyFeatures: ["Premium Package", "3-Row Seating", "Luxury Comfort"],
      metaTitle: "2016 Buick Enclave Premium - T-Rex Motors Richmond IN",
      metaDescription: "2016 Buick Enclave Premium with 106,721 miles. Luxury 3-row SUV."
    },
    {
      slug: "2014-jeep-grand-cherokee-red-12999",
      title: "2014 Jeep Grand Cherokee",
      description: "Capable SUV with off-road prowess and on-road comfort.",
      price: 12999,
      year: "2014",
      make: "Jeep",
      model: "Grand Cherokee",
      vin: "1C4RJFAG4EC123456",
      stockNumber: "JGC001",
      mileage: "120955",
      exteriorColor: "Red",
      interiorColor: "Grey",
      engine: "3.6L V6",
      transmission: "8-Speed Automatic",
      driveType: "4WD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6824d9349cd8fb125e9a1fe9.jpeg"],
      keyFeatures: ["4WD Capability", "Towing Package", "Trail Rated"],
      metaTitle: "2014 Jeep Grand Cherokee - T-Rex Motors Richmond IN",
      metaDescription: "2014 Jeep Grand Cherokee with 120,955 miles. Capable 4WD SUV."
    },
    {
      slug: "2014-jeep-grand-cherokee-grey-12999",
      title: "2014 Jeep Grand Cherokee",
      description: "Well-maintained SUV with proven reliability and versatility.",
      price: 12999,
      year: "2014",
      make: "Jeep",
      model: "Grand Cherokee",
      vin: "1C4RJFAG8EC123456",
      stockNumber: "JGC002",
      mileage: "135403",
      exteriorColor: "Grey",
      interiorColor: "Grey",
      engine: "3.6L V6",
      transmission: "8-Speed Automatic",
      driveType: "4WD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6824d99920806f427eedfcac.jpeg"],
      keyFeatures: ["4WD System", "Reliable V6", "Spacious Interior"],
      metaTitle: "2014 Jeep Grand Cherokee Grey - T-Rex Motors Richmond IN",
      metaDescription: "2014 Jeep Grand Cherokee with 135,403 miles. Reliable 4WD SUV."
    },
    {
      slug: "2007-jeep-patriot-high-alt-white-2999",
      title: "2007 Jeep Patriot High Alt",
      description: "Affordable compact SUV with rugged capability and 4WD system.",
      price: 2999,
      year: "2007",
      make: "Jeep",
      model: "Patriot",
      vin: "1J8FF28W97D123456",
      stockNumber: "JP001",
      mileage: "212619",
      exteriorColor: "White",
      interiorColor: "Black",
      engine: "2.4L 4-Cylinder",
      transmission: "CVT Automatic",
      driveType: "4WD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/68042afc29d629c59c352a2b.png"],
      keyFeatures: ["Affordable", "4WD Capability", "Compact SUV"],
      metaTitle: "2007 Jeep Patriot High Altitude - T-Rex Motors Richmond IN",
      metaDescription: "2007 Jeep Patriot High Altitude with 212,619 miles. Affordable 4WD SUV."
    },
    {
      slug: "2016-cadillac-ats-black-15999",
      title: "2016 Cadillac ATS",
      description: "Luxury compact sedan with sport-tuned performance and premium features.",
      price: 15999,
      year: "2016",
      make: "Cadillac",
      model: "ATS",
      vin: "1G6AG5RX0G0123456",
      stockNumber: "CA001",
      mileage: "102594",
      exteriorColor: "Black",
      interiorColor: "Grey",
      engine: "2.0L Turbo 4-Cylinder",
      transmission: "8-Speed Automatic",
      driveType: "RWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6806481698e519ee0d7bb864.jpeg"],
      keyFeatures: ["Turbo Engine", "Sport Suspension", "Luxury Interior"],
      metaTitle: "2016 Cadillac ATS - T-Rex Motors Richmond IN",
      metaDescription: "2016 Cadillac ATS with 102,594 miles. Luxury compact sedan with turbo power."
    },
    {
      slug: "2016-ford-edge-titanium-red-12999",
      title: "2016 Ford Edge Titanium",
      description: "Premium midsize SUV with advanced technology and comfortable ride.",
      price: 12999,
      year: "2016",
      make: "Ford",
      model: "Edge",
      vin: "2FMPK4K90GBA123456",
      stockNumber: "FE001",
      mileage: "140736",
      exteriorColor: "Red",
      interiorColor: "Grey",
      engine: "3.5L V6",
      transmission: "6-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/680647ec43729000f6c14d33.jpeg"],
      keyFeatures: ["Titanium Package", "Premium Tech", "V6 Power"],
      metaTitle: "2016 Ford Edge Titanium - T-Rex Motors Richmond IN",
      metaDescription: "2016 Ford Edge Titanium with 140,736 miles. Premium midsize SUV."
    },
    {
      slug: "2018-honda-civic-black-15991",
      title: "2018 Honda Civic",
      description: "Reliable compact sedan with excellent fuel economy and modern safety features.",
      price: 15991,
      year: "2018",
      make: "Honda",
      model: "Civic",
      vin: "2HGFC2F50JH123456",
      stockNumber: "HC002",
      mileage: "118230",
      exteriorColor: "Black",
      interiorColor: "Grey",
      engine: "2.0L 4-Cylinder",
      transmission: "CVT Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6806470b98e5195b227bb78e.jpeg"],
      keyFeatures: ["Honda Sensing", "Fuel Efficient", "Reliable"],
      metaTitle: "2018 Honda Civic - T-Rex Motors Richmond IN",
      metaDescription: "2018 Honda Civic with 118,230 miles. Reliable compact sedan with great fuel economy."
    },
    {
      slug: "2019-chevrolet-equinox-white-13991",
      title: "2019 Chevrolet Equinox",
      description: "Modern compact SUV with efficient turbo engine and spacious interior.",
      price: 13991,
      year: "2019",
      make: "Chevrolet",
      model: "Equinox",
      vin: "2GNAXSEV4K6123456",
      stockNumber: "CE001",
      mileage: "122182",
      exteriorColor: "White",
      interiorColor: "Grey",
      engine: "1.5L Turbo 4-Cylinder",
      transmission: "CVT Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6806469f773e1668e4f7c692.jpeg"],
      keyFeatures: ["Turbo Engine", "Modern Interior", "Efficient"],
      metaTitle: "2019 Chevrolet Equinox - T-Rex Motors Richmond IN",
      metaDescription: "2019 Chevrolet Equinox with 122,182 miles. Modern compact SUV with turbo power."
    },
    {
      slug: "2019-chevrolet-cruze-red-9991",
      title: "2019 Chevrolet Cruze",
      description: "Efficient compact sedan with modern technology and comfortable interior.",
      price: 9991,
      year: "2019",
      make: "Chevrolet",
      model: "Cruze",
      vin: "1G1BC5SM8K7123456",
      stockNumber: "CC002",
      mileage: "133162",
      exteriorColor: "Red",
      interiorColor: "Grey",
      engine: "1.4L Turbo 4-Cylinder",
      transmission: "CVT Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/680646de437290c1dec14c22.jpeg"],
      keyFeatures: ["Turbo Engine", "Great Value", "Modern Tech"],
      metaTitle: "2019 Chevrolet Cruze - T-Rex Motors Richmond IN",
      metaDescription: "2019 Chevrolet Cruze with 133,162 miles. Efficient compact sedan with turbo power."
    },
    {
      slug: "2013-chevrolet-equinox-lt-white-10491",
      title: "2013 Chevrolet Equinox LT",
      description: "Dependable midsize SUV with proven reliability and family-friendly features.",
      price: 10491,
      year: "2013",
      make: "Chevrolet",
      model: "Equinox",
      vin: "2GNFLGE54D6123456",
      stockNumber: "CE002",
      mileage: "110451",
      exteriorColor: "White",
      interiorColor: "Grey",
      engine: "2.4L 4-Cylinder",
      transmission: "6-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/680648d198e5194f847bb902.jpeg"],
      keyFeatures: ["LT Package", "Reliable", "Family SUV"],
      metaTitle: "2013 Chevrolet Equinox LT - T-Rex Motors Richmond IN",
      metaDescription: "2013 Chevrolet Equinox LT with 110,451 miles. Dependable family SUV."
    },
    {
      slug: "2013-ford-flex-sel-white-8481",
      title: "2013 Ford Flex SEL",
      description: "Unique 3-row crossover with spacious interior and smooth highway ride.",
      price: 8481,
      year: "2013",
      make: "Ford",
      model: "Flex",
      vin: "2FMGK5C89DBA123456",
      stockNumber: "FF001",
      mileage: "155359",
      exteriorColor: "White",
      interiorColor: "Grey",
      engine: "3.5L V6",
      transmission: "6-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/680648a7437290bcf0c14df5.jpeg"],
      keyFeatures: ["SEL Package", "3-Row Seating", "Spacious"],
      metaTitle: "2013 Ford Flex SEL - T-Rex Motors Richmond IN",
      metaDescription: "2013 Ford Flex SEL with 155,359 miles. Unique 3-row crossover with space."
    },
    {
      slug: "2015-chrysler-200-s-silver-10991",
      title: "2015 Chrysler 200 S",
      description: "Stylish midsize sedan with sport-tuned suspension and premium interior.",
      price: 10991,
      year: "2015",
      make: "Chrysler",
      model: "200",
      vin: "1C3CCCAB6FN123456",
      stockNumber: "CR001",
      mileage: "122182",
      exteriorColor: "Silver",
      interiorColor: "Silver",
      engine: "2.4L 4-Cylinder",
      transmission: "9-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/680648444fb6bc1cabdce7cc.jpeg"],
      keyFeatures: ["S Package", "Sport Suspension", "Premium Interior"],
      metaTitle: "2015 Chrysler 200 S - T-Rex Motors Richmond IN",
      metaDescription: "2015 Chrysler 200 S with 122,182 miles. Stylish midsize sedan with sport package."
    },
    {
      slug: "2015-kia-forte-black-6999",
      title: "2015 Kia Forte",
      description: "Affordable compact sedan with excellent value and reliability.",
      price: 6999,
      year: "2015",
      make: "Kia",
      model: "Forte",
      vin: "KNAFK4A68F5123456",
      stockNumber: "KF002",
      mileage: "121634",
      exteriorColor: "Black",
      interiorColor: "Grey",
      engine: "2.0L 4-Cylinder",
      transmission: "6-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6824dc187410f98cbca2b51f.jpeg"],
      keyFeatures: ["Great Value", "Reliable", "Fuel Efficient"],
      metaTitle: "2015 Kia Forte - T-Rex Motors Richmond IN",
      metaDescription: "2015 Kia Forte with 121,634 miles. Affordable compact sedan with great value."
    },
    {
      slug: "2018-honda-civic-white-17999",
      title: "2018 Honda Civic",
      description: "Clean and reliable compact sedan with excellent fuel economy and safety features.",
      price: 17999,
      year: "2018",
      make: "Honda",
      model: "Civic",
      vin: "2HGFC2F58JH123456",
      stockNumber: "HC003",
      mileage: "98964",
      exteriorColor: "White",
      interiorColor: "Grey",
      engine: "2.0L 4-Cylinder",
      transmission: "CVT Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6824db025b0a0b47b2a26c4d.jpeg"],
      keyFeatures: ["Low Mileage", "Honda Sensing", "Excellent Condition"],
      metaTitle: "2018 Honda Civic White - T-Rex Motors Richmond IN",
      metaDescription: "2018 Honda Civic with 98,964 miles. Clean and reliable with low mileage."
    },
    {
      slug: "2015-chevy-trax-white-9991",
      title: "2015 Chevy Trax",
      description: "Compact SUV with good fuel economy and higher seating position.",
      price: 9991,
      year: "2015",
      make: "Chevrolet",
      model: "Trax",
      vin: "3GNCJKSB8FL123456",
      stockNumber: "CT001",
      mileage: "92062",
      exteriorColor: "White",
      interiorColor: "Camel",
      engine: "1.4L Turbo 4-Cylinder",
      transmission: "6-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/680648774372902f44c14de1.jpeg"],
      keyFeatures: ["Compact SUV", "Turbo Engine", "Good MPG"],
      metaTitle: "2015 Chevrolet Trax - T-Rex Motors Richmond IN",
      metaDescription: "2015 Chevrolet Trax with 92,062 miles. Compact SUV with turbo power."
    },
    {
      slug: "2017-chevrolet-traverse-lt-red-15999",
      title: "2017 Chevrolet Traverse LT",
      description: "Large 3-row SUV with plenty of space for families and cargo.",
      price: 15999,
      year: "2017",
      make: "Chevrolet",
      model: "Traverse",
      vin: "1GNKRFKD4HJ123456",
      stockNumber: "CT002",
      mileage: "91106",
      exteriorColor: "Red",
      interiorColor: "Grey",
      engine: "3.6L V6",
      transmission: "9-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/6806474363925e08e0879442.jpeg"],
      keyFeatures: ["LT Package", "3-Row Seating", "V6 Power"],
      metaTitle: "2017 Chevrolet Traverse LT - T-Rex Motors Richmond IN",
      metaDescription: "2017 Chevrolet Traverse LT with 91,106 miles. Large family SUV with 3 rows."
    },
    {
      slug: "2016-jeep-patriot-high-alt-red-11999",
      title: "2016 Jeep Patriot High Alt",
      description: "Rugged compact SUV with 4WD capability and affordable pricing.",
      price: 11999,
      year: "2016",
      make: "Jeep",
      model: "Patriot",
      vin: "1C4NJPBB5GD123456",
      stockNumber: "JP002",
      mileage: "124924",
      exteriorColor: "Red",
      interiorColor: "Black",
      engine: "2.4L 4-Cylinder",
      transmission: "CVT Automatic",
      driveType: "4WD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/680647b49146b5a04e5a37c7.jpeg"],
      keyFeatures: ["High Altitude Package", "4WD", "Trail Rated"],
      metaTitle: "2016 Jeep Patriot High Altitude - T-Rex Motors Richmond IN",
      metaDescription: "2016 Jeep Patriot High Altitude with 124,924 miles. Rugged 4WD SUV."
    },
    {
      slug: "2017-buick-enclave-black-14977",
      title: "2017 Buick Enclave",
      description: "Premium 3-row SUV with luxury features and smooth ride quality.",
      price: 14977,
      year: "2017",
      make: "Buick",
      model: "Enclave",
      vin: "5GAKVBKD8HJ123456",
      stockNumber: "BE002",
      mileage: "133045",
      exteriorColor: "Black",
      interiorColor: "Grey",
      engine: "3.6L V6",
      transmission: "9-Speed Automatic",
      driveType: "FWD",
      status: "for-sale",
      images: ["https://images.leadconnectorhq.com/image/f_webp/q_80/r_1200/u_https://assets.cdn.filesafe.space/QjiQRR74D1pxPF7I8fcC/media/68064779baaef90399a2d02f.jpeg"],
      keyFeatures: ["Premium SUV", "3-Row Luxury", "V6 Engine"],
      metaTitle: "2017 Buick Enclave - T-Rex Motors Richmond IN",
      metaDescription: "2017 Buick Enclave with 133,045 miles. Premium 3-row luxury SUV."
    }
  ];

  await db.insert(vehicles).values(trexVehicles);
  
  console.log(`Database seeded successfully with ${trexVehicles.length} T-Rex Motors vehicles!`);
}

// Run if called directly
if (import.meta.url === `file://${process.argv[1]}`) {
  seedTrexVehicles().catch(console.error);
}

export { seedTrexVehicles };